language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"

install:
  - "pip install -r requirements"

script: nosetests

after_success:
  - if [ "${COVERAGE}" == "1" ]; then coveralls; fi
